spring:
    main:
            allow-circular-references: true
    application: 
        name: hospitalization2206829225
    datasource: 
        url: jdbc:postgresql://localhost:15001/hospitalization2206829225
        username: postgres
        password: secret99
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create
server:
    port: 8083
hospitalization2206829225:
    app:
        jwtSecret: "hPjbJwZKskRmCnzroyAZfglqSKexYmxKeYPvSvJ"
        jwtExpirationMs: 86400000